/*
BudgetKeep
Domain: Identity & Security
Script: 901_RollbackSeed.sql
*/

SET NOCOUNT ON;
SET XACT_ABORT ON;

BEGIN TRANSACTION;

DELETE FROM dbo.SystemConfiguration
WHERE Code IN
(
    'SECURITY_MAX_FAILED_LOGIN_ATTEMPTS',
    'SECURITY_LOCKOUT_DURATION_MINUTES',
    'SECURITY_MAX_LOCKOUT_COUNT',
    'SECURITY_LOCKOUT_COUNT_WINDOW_DAYS'
);

DELETE FROM dbo.ConfigurationDataType
WHERE Code IN ('INT','DECIMAL','BOOLEAN','STRING','DATETIME2');

COMMIT TRANSACTION;
